### ISSUE TITLE
Uncaught ReferenceError: 'spierdalaj' is not defined

### ISSUE THREAD

**Issue by theSaintKappa** [GinoWasTaken/example-website-2022#1]
## The problem:
Upon trying to run the code either through a browser or Node.js,
I get this error from file `scripts.js` <sub>(plural cuz there is more than one of them scripts apparently)</sub>:
`Uncaught ReferenceError: 'spierdalaj' is not defined`
<br>

## The expected behavior:
**spierdalaj**
<br>

## Reproducible code sample:
```javascript
spierdalaj
```
<br>

## Further details:

* Environments:
  * Node.js - v18.13.0
  * Node.js - v19.5.0
  * Google Chrome 109.0.5414.119 (Official Build) (64-bit)
* OS:
  * Windows 11 Version 22H2 (Build 22621.1105)
  * Ubuntu 22.04.1 LTS

### Really hope for this to be resolved soon 🙏🤞

**Comment by GinoMoses** [comment]
### Oh no! fr?
Thank you for submitting this issue, I am terribly sorry for the inconvenience. 
After hours of hard work and debugging I managed to successfully resolve the issue.

Somehow this beginner mistake has found a way into my masterpiece, delightful, well-thought-of and otherwise flawless code.
Turns out `spierdalaj` was simply supposed to declare a function, but what happened is I completely forgot to write the rest of the code 😯. You might even say that I forgor 💀.

Instead of the completely wrong
```js
spierdalaj
````
it was, **obviously**, supposed to be this
```js
spierdalaj = () => {
	const colors = ["rgba(255, 0, 0, 1)",
        "rgba(255, 154, 0, 1)",
        "rgba(208, 222, 33, 1)",
        "rgba(79, 220, 74, 1)",
        "rgba(63, 218, 216, 1)",
        "rgba(47, 201, 226, 1)",
        "rgba(28, 127, 238, 1)",
        "rgba(95, 21, 242, 1)",
        "rgba(186, 12, 248, 1)",
        "rgba(251, 7, 217, 1)",
        "rgba(255, 0, 0, 1)"]
	
	const body = document.querySelector("body");
	body.innerHTML = "<h1>spierdalaj</h1>";
	body.style = "display: flex; min-height: 100vh; justify-content: center; align-items: center; color: white; font-size: 7rem";
	let i = 100;
	let dir = 1;
	setInterval(() => {
			body.style.minHeight = `${i}vh`;
			
			if(i>=180) dir=0;
			if(i<=20) dir=1;
			if(dir==1) i++;
			if(dir==0) i--;
			
			body.style.color = colors[Math.floor(Math.random() * 11)];
	},5)
}
```

The function is executed upon clicking the `a` element on the right side of the navbar that reads "Lorem Ipsum".
To be precise, I am talking about line number 22 of the HTML file.

```html
  <a id="navbar-side-item" onclick="spierdalaj()")>Lorem Ipsum</a>
```

I am glad I could ~~waste~~ spend some time fixing this issue and I hope that this fantastic project will prove useful to you in the future.

**Comment by theSaintKappa** [comment]
I'm in awe while looking at your solution to this issue and I want to express my sincerest gratitude for the tireless efforts you have put forth in solving the bug that had been plaguing this repository. Your dedication to ensuring the smooth functioning of this project is truly commendable, and your swift resolution of the issue was nothing short of remarkable.

It is not often that one comes across a developer with such a keen eye for detail and an unwavering commitment to excellence. Your technical acumen is truly impressive, and it is clear that you take your craft seriously. It is developers like yourself that set the standard for excellence in the industry.

Once again, thank you for your hard work and dedication. Your contributions to the field of software development are truly invaluable, and we are all better off for it. With all that said, I'm closing this issue and hoping that others whom one day may happen upon it, shall learn from it, as well as admire what happened on this very day. Oh... and did I mention, I use arch btw?
